# Generated by Django 3.1.10 on 2021-05-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0004_initial_part_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('tunnel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending-configuration', max_length=30)),
                ('tunnel_type', models.CharField(default='ipsec-tunnel', max_length=30)),
                ('src_address', models.CharField(blank=True, max_length=28)),
                ('dst_address', models.CharField(blank=True, max_length=28)),
                ('src_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
            ],
            options={
                'ordering': ['tunnel_id'],
            },
        ),
    ]
