# Generated by Django 3.1.14 on 2022-02-14 22:49

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dcim", "0007_device_secrets_group"),
        ("extras", "0021_customfield_changelog_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPTPTunnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="pending-configuration", max_length=30)),
                ("tunnel_type", models.CharField(default="pptp-tunnel", max_length=30)),
                ("tunnel_mtu", models.IntegerField(default=1500)),
                ("clns_mtu", models.IntegerField(default=1500)),
                ("encapsulation", models.CharField(default="gre", max_length=30)),
                (
                    "dst_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pptptunnels", to="dcim.device"
                    ),
                ),
                (
                    "dst_interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pptptunnels", to="dcim.interface"
                    ),
                ),
                (
                    "src_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="basetunnels", to="dcim.device"
                    ),
                ),
                (
                    "src_interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="basetunnels", to="dcim.interface"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ISAKMPPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("version", models.CharField(default="ike1", max_length=100)),
                ("mode", models.CharField(default="main", max_length=100)),
                ("identification", models.CharField(default="address", max_length=100)),
                ("nat", models.BooleanField(default=False)),
                ("nat_keepalive", models.IntegerField(default=3600)),
                ("authentication", models.CharField(default="pre-share", max_length=100)),
                ("hash", models.CharField(default="hmac-md5", max_length=100)),
                ("dh_group", models.CharField(default="group1", max_length=100)),
                ("pfs", models.BooleanField(default=False)),
                ("lifetime", models.IntegerField(default=86400)),
                (
                    "secrets_group",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.secretsgroup"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
